services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "89:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - .:/var/www
        depends_on:
            - db
            - redis
        networks:
            - laravel

    db:
        image: mysql
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_USER: ${DB_USERNAME:-laravel}
            MYSQL_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
        volumes:
            - ./docker/mysql:/var/lib/mysql
        ports:
            - "3389:3306"
        networks:
            - laravel

    redis:
        image: redis:latest
        container_name: redis
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
