@baseUrl = http://localhost:89

###
# Listar todos os usuários
# @name getUsers
GET {{baseUrl}}/api/users
Accept: application/json
Authorization: Bearer 6|ocZ8aIjIqxydZ7YaQwsYegUPu6LG7PQ0xmSO44pB45c7f5c2

###
# Criar um novo usuário
# @name createUser
POST {{baseUrl}}/api/users
Content-Type: application/json
Accept: application/json

{
  "name": "Mateus Alecrin 2",
  "email": "mateus.alecrin2@hotmail.com",
  "password": "123456"
}

###
# Buscar um usuário por ID
# @name getUser
GET {{baseUrl}}/api/users/1
Accept: application/json

###
# Atualizar usuário por ID
# @name updateUser
PUT {{baseUrl}}/api/users/1
Content-Type: application/json
Accept: application/json

{
  "name": "Mateus",
  "password": "784892"
}

###
# Deletar um usuário por ID
# @name deleteUser
DELETE {{baseUrl}}/api/users/3
Accept: application/json



